apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: langchain-tutorial
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '0'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/langchain-tutorial
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: '8080'
        - name: GOOGLE_API_KEY
          value: YOUR_API_KEY_HERE
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
